# Generated by Django 2.1.4 on 2020-07-23 02:43

from django.db import migrations
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=post.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
