# Generated by Django 2.1.4 on 2020-07-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
